const SHOW_SNACKBAR = "SHOW_SNACK_BAR";
const HIDE_SNACKBAR = "HIDE_SNACK_BAR";
const SHOW_LOADING = "SHOW_LOADING";
const HIDE_LOADING = "HIDE_LOADING";

const ADD_USER = "ADD_USER";
const EDIT_USER = "EDIT_USER";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const GET_ALL_USER = "GET_ALL_USER";
const GET_USER = "GET_USER";
const UPDATE_ROLE_USER = "UPDATE_ROLE_USER";
const SIGN_IN_SUCCESS = "SIGN_IN";
const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
const GET_ALL_SHIFT_SUCCESS = "GET_ALL_SHIFT_SUCCESS";
const GET_TIME_KEEPING_NOTIFICATION_SUCCESS = "GET_TIME_KEEPING_NOTIFICATION_SUCCESS";
const UPDATE_TIME_KEEPING_NOTIFICATION_SUCCESS = "UPDATE_TIME_KEEPING_NOTIFICATION_SUCCESS";
const UPDATE_SHIFTS_SUCCESS = "UPDATE_SHIFTS_SUCCESS";
const UPDATE_IS_ALL_VALID = "UPDATE_IS_ALL_VALID";
const GET_ALL_ORGANIZATION_SUCCESS = "GET_ALL_ORGANIZATION_SUCCESS";
const ADD_ORGANIZATION_SUCCESS = "ADD_ORGANIZATION_SUCCESS";
const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
const GET_ALL_FEATURES_SUCCESS = "GET_ALL_FEATURES_SUCCESS";
const GET_ALL_LOG_SUCCESS = "GET_ALL_LOG_SUCCESS";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_MY_INFO_SUCCESS = "UPDATE_MY_INFO_SUCCESS";
const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
const GET_ALL_CAMERA_SUCCESS = "GET_ALL_CAMERA_SUCCESS";
const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
const GET_ALL_LOCATION_SUCCESS = "GET_ALL_LOCATION_SUCCESS";
const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
const CHANGE_MANAGER_SUCCESS = "CHANGE_MANAGER_SUCCESS";
const ADD_CAMERA_SUCCESS = "ADD_CAMERA_SUCCESS";
const GET_ALL_BRAND_SUCCESS = "GET_ALL_BRAND_SUCCESS";
const DELETE_CAMERA_SUCCESS = "DELETE_CAMERA_SUCCESS";
const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
const UPDATE_CAMERA_SUCCESS = "UPDATE_CAMERA_SUCCESS";
const GET_ALL_IN_OUT_HISTORIES_SUCCESS = "GET_ALL_IN_OUT_HISTORIES_SUCCESS";
const ADD_IN_OUT_HISTORY_SUCCESS = "ADD_IN_OUT_HISTORY_SUCCESS";
const GET_ALL_NOTIFICATION_HISTORIES_SUCCESS = "GET_ALL_NOTIFICATION_HISTORIES_SUCCESS";
const GET_ALL_AREA_RESTRICTION_SUCCESS = "GET_ALL_AREA_RESTRICTION_SUCCESS";
const ADD_AREA_RESTRICTION_SUCCESS = "ADD_AREA_RESTRICTION_SUCCESS";
const UPDATE_AREA_RESTRICTION_SUCCESS = "UPDATE_AREA_RESTRICTION_SUCCESS";
const DELETE_AREA_RESTRICTION_SUCCESS = "DELETE_AREA_RESTRICTION_SUCCESS";
const GET_ALL_AREA_RESTRICTION_NOTIFICATION_SUCCESS =
  "GET_ALL_AREA_RESTRICTION_NOTIFICATION_SUCCESS";
const UPDATE_AREA_RESTRICTION_NOTIFICATION_SUCCESS = "UPDATE_AREA_RESTRICTION_NOTIFICATION_SUCCESS";
const UPDATE_AREA_USER_ATTENDANCE_CHOOSED = "UPDATE_AREA_USER_ATTENDANCE_CHOOSED";
const GET_USER_ATTENDANCE_ITEMS_SUCCESS = "GET_USER_ATTENDANCE_ITEMS_SUCCESS";
const ADD_USER_ATTENDANCE_ITEM_SUCCESS = "ADD_USER_ATTENDANCE_ITEM_SUCCESS";
const UPDATE_USER_ATTENDANCE_ITEM_SUCCESS = "UPDATE_USER_ATTENDANCE_ITEM_SUCCESS";
const UPDATE_CONFIRM_AUDIO = "UPDATE_CONFIRM_AUDIO";
const UPDATE_STATUS_AUDIO = "UPDATE_STATUS_AUDIO";
const UPDATE_HAS_NOTIFICATION_AUDIO = "UPDATE_HAS_NOTIFICATION_AUDIO";
const UPDATE_EMPLOYEE_CHOOSED = "UPDATE_EMPLOYEE_CHOOSED";
const UPDATE_AREA_RESTRICTION_CHOOSED = "UPDATE_AREA_RESTRICTION_CHOOSED";
const UPDATE_CAMERA_RESTRICTION_CHOOSED = "UPDATE_CAMERA_RESTRICTION_CHOOSED";
const UPDATE_CAMERA_LOCATION_CHOOSED = "UPDATE_CAMERA_LOCATION_CHOOSED";
const UPDATE_FILTER_USER_LOG = "UPDATE_FILTER_USER_LOG";
const UPDATE_FILTER_NOTIFICATION_HISTORY = "UPDATE_FILTER_NOTIFICATION_HISTORY";
const UPDATE_TOGGLE_NOTIFICATION_HISTORY = "UPDATE_TOGGLE_NOTIFICATION_HISTORY";
const UPDATE_FILTER_CAMERA = "UPDATE_FILTER_CAMERA";
const UPDATE_FILTER_EPLOYEE = "UPDATE_FILTER_EPLOYEE";
const UPDATE_NOTIFICATION_STATUS = "UPDATE_NOTIFICATION_STATUS";
const RE_SEND_CODE_EMPLOYEE_SUCCESS = "RE_SEND_CODE_EMPLOYEE_SUCCESS";
const UPDATE_FILTER_USER = "UPDATE_FILTER_USER";
const ADD_GUEST = "ADD_GUEST";
const UPDATE_FILTER_IN_OUT_HISTORY = "UPDATE_FILTER_IN_OUT_HISTORY";
const ADD_CAMERA_LIST_ID_SUCCESS = "ADD_CAMERA_LIST_ID_SUCCESS";
const UPDATE_FILTER_ORGANIZATION = "UPDATE_FILTER_ORGANIZATION";

export {
  SHOW_SNACKBAR,
  HIDE_SNACKBAR,
  SHOW_LOADING,
  HIDE_LOADING,
  ADD_USER,
  EDIT_USER,
  DELETE_USER_SUCCESS,
  GET_USER,
  GET_ALL_USER,
  UPDATE_ROLE_USER,
  SIGN_IN_SUCCESS,
  GET_ALL_USER_SUCCESS,
  GET_ALL_ROLE_SUCCESS,
  GET_ALL_SHIFT_SUCCESS,
  GET_TIME_KEEPING_NOTIFICATION_SUCCESS,
  UPDATE_TIME_KEEPING_NOTIFICATION_SUCCESS,
  UPDATE_SHIFTS_SUCCESS,
  GET_ALL_ORGANIZATION_SUCCESS,
  ADD_ORGANIZATION_SUCCESS,
  DELETE_ORGANIZATION_SUCCESS,
  UPDATE_ORGANIZATION_SUCCESS,
  GET_ALL_FEATURES_SUCCESS,
  GET_ALL_LOG_SUCCESS,
  UPDATE_USER_SUCCESS,
  UPDATE_MY_INFO_SUCCESS,
  LOG_OUT_SUCCESS,
  GET_ALL_CAMERA_SUCCESS,
  GET_ALL_EMPLOYEE_SUCCESS,
  ADD_EMPLOYEE_SUCCESS,
  UPDATE_EMPLOYEE_SUCCESS,
  GET_ALL_LOCATION_SUCCESS,
  ADD_LOCATION_SUCCESS,
  UPDATE_LOCATION_SUCCESS,
  DELETE_LOCATION_SUCCESS,
  CHANGE_MANAGER_SUCCESS,
  ADD_CAMERA_SUCCESS,
  GET_ALL_BRAND_SUCCESS,
  DELETE_CAMERA_SUCCESS,
  DELETE_EMPLOYEE_SUCCESS,
  UPDATE_CAMERA_SUCCESS,
  GET_ALL_IN_OUT_HISTORIES_SUCCESS,
  ADD_IN_OUT_HISTORY_SUCCESS,
  GET_ALL_NOTIFICATION_HISTORIES_SUCCESS,
  GET_ALL_AREA_RESTRICTION_SUCCESS,
  ADD_AREA_RESTRICTION_SUCCESS,
  UPDATE_AREA_RESTRICTION_SUCCESS,
  DELETE_AREA_RESTRICTION_SUCCESS,
  GET_ALL_AREA_RESTRICTION_NOTIFICATION_SUCCESS,
  UPDATE_AREA_RESTRICTION_NOTIFICATION_SUCCESS,
  UPDATE_AREA_USER_ATTENDANCE_CHOOSED,
  GET_USER_ATTENDANCE_ITEMS_SUCCESS,
  ADD_USER_ATTENDANCE_ITEM_SUCCESS,
  UPDATE_USER_ATTENDANCE_ITEM_SUCCESS,
  UPDATE_CONFIRM_AUDIO,
  UPDATE_STATUS_AUDIO,
  UPDATE_HAS_NOTIFICATION_AUDIO,
  UPDATE_EMPLOYEE_CHOOSED,
  UPDATE_AREA_RESTRICTION_CHOOSED,
  UPDATE_CAMERA_RESTRICTION_CHOOSED,
  UPDATE_CAMERA_LOCATION_CHOOSED,
  UPDATE_FILTER_USER_LOG,
  UPDATE_FILTER_NOTIFICATION_HISTORY,
  UPDATE_FILTER_CAMERA,
  UPDATE_FILTER_EPLOYEE,
  UPDATE_NOTIFICATION_STATUS,
  UPDATE_TOGGLE_NOTIFICATION_HISTORY,
  RE_SEND_CODE_EMPLOYEE_SUCCESS,
  UPDATE_FILTER_USER,
  ADD_GUEST,
  UPDATE_FILTER_IN_OUT_HISTORY,
  ADD_CAMERA_LIST_ID_SUCCESS,
  UPDATE_FILTER_ORGANIZATION,
  UPDATE_IS_ALL_VALID,
};
